### ISSUE TITLE
Desasparecidos

### ISSUE THREAD

**Issue by beppe9000** [michaelzangl/minebot#114]
For some strange reason there are some random players (but if player X does, it always will) that are completely absent from the game: nothing is rendered, even name tags. Their only traces are chat messages and chat auto completion.
This only happens with Minebot (I've checked with no mods and they are rendered. adding minebot 1.8 & 1.8.9 makes them disappear randomly) so I'm reporting here. 

If they re-log they may become visible again.

**UPDATE**
I catched this:

```
[01:06:29] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_77]
    at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_77]
    at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1070) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:380) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnPlayer(NetHandlerPlayClient.java:531) ~[NetHandlerPlayClient.class:?]
    at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:85) ~[S0CPacketSpawnPlayer.class:?]
    at net.minecraft.network.play.server.S0CPacketSpawnPlayer.processPacket(S0CPacketSpawnPlayer.java:17) ~[S0CPacketSpawnPlayer.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_77]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_77]
    at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
    ... 15 more
```

So how is Minebot interfering with the player spawn handler?

```
   public void handleSpawnPlayer(S0CPacketSpawnPlayer packetIn)
    {
        PacketThreadUtil.checkThreadAndEnqueue(packetIn, this, this.gameController);
        double d0 = (double)packetIn.getX() / 32.0D;
        double d1 = (double)packetIn.getY() / 32.0D;
        double d2 = (double)packetIn.getZ() / 32.0D;
        float f = (float)(packetIn.getYaw() * 360) / 256.0F;
        float f1 = (float)(packetIn.getPitch() * 360) / 256.0F;
        EntityOtherPlayerMP entityotherplayermp = new EntityOtherPlayerMP(this.gameController.theWorld, this.getPlayerInfo(packetIn.getPlayer()).getGameProfile());
    //continues...
    }
```

I explored the problem and the major symptom is that the `EntityOtherPlayerMP` construction fails (and so it is never added to the world -> no rendering) because `this.getPlayerInfo` returns a `null`:

```
    public NetworkPlayerInfo getPlayerInfo(UUID p_175102_1_)
    {
        return (NetworkPlayerInfo)this.playerInfoMap.get(p_175102_1_);
    }
```

There is only one place where the underlying `playerInfoMap` is manipulated: the packet handler for the tab menu player list, and only in the case of a `ADD_PLAYER` action.

```
@SuppressWarnings("incomplete-switch")
    public void handlePlayerListItem(S38PacketPlayerListItem packetIn)
    {
        PacketThreadUtil.checkThreadAndEnqueue(packetIn, this, this.gameController);

        for (S38PacketPlayerListItem.AddPlayerData s38packetplayerlistitem$addplayerdata : packetIn.func_179767_a())
        {
            if (packetIn.func_179768_b() == S38PacketPlayerListItem.Action.REMOVE_PLAYER)
            {
                this.playerInfoMap.remove(s38packetplayerlistitem$addplayerdata.getProfile().getId());
            }
            else
            {
                NetworkPlayerInfo networkplayerinfo = (NetworkPlayerInfo)this.playerInfoMap.get(s38packetplayerlistitem$addplayerdata.getProfile().getId());

                if (packetIn.func_179768_b() == S38PacketPlayerListItem.Action.ADD_PLAYER)
                {
                    networkplayerinfo = new NetworkPlayerInfo(s38packetplayerlistitem$addplayerdata);
                    this.playerInfoMap.put(networkplayerinfo.getGameProfile().getId(), networkplayerinfo);
                }

                if (networkplayerinfo != null)
                {
                    switch (packetIn.func_179768_b())
                    {
                        case ADD_PLAYER:
                            networkplayerinfo.setGameType(s38packetplayerlistitem$addplayerdata.getGameMode());
                            networkplayerinfo.setResponseTime(s38packetplayerlistitem$addplayerdata.getPing());
                            break;
                        case UPDATE_GAME_MODE:
                            networkplayerinfo.setGameType(s38packetplayerlistitem$addplayerdata.getGameMode());
                            break;
                        case UPDATE_LATENCY:
                            networkplayerinfo.setResponseTime(s38packetplayerlistitem$addplayerdata.getPing());
                            break;
                        case UPDATE_DISPLAY_NAME:
                            networkplayerinfo.setDisplayName(s38packetplayerlistitem$addplayerdata.getDisplayName());
                    }
                }
            }
        }
    }
```

The simple explanation would be that the server sends packets in the wrong order, but that's not the case, as it works normally without mods installed.

**Comment by beppe9000** [comment]
I don't know if it is the specific server I'm playing on or Minebot or a combination of the two, but here is my workaround. 

This function needs to be added to the MinebotNetHandler class:

 ```
	@Override
	public void handleSpawnPlayer(S0CPacketSpawnPlayer packetIn) {
		UUID player_uuid = packetIn.getPlayer();
		NetworkPlayerInfo player_info = this.getPlayerInfo(player_uuid);

		if (player_info == null) {
			System.out.println("PLAYER INFO IS NULL FOR PLAYER "+player_uuid+" -> SIMULATING CREATION");
			GameProfile gprof = new GameProfile(player_uuid,
					String.valueOf(player_uuid).replaceAll("-", "").substring(0, 15));
			player_info = new NetworkPlayerInfo(gprof);
			Map<UUID, NetworkPlayerInfo> playerInfoMapRef = null;

			Field fs = null;
			try {
				fs = this.getClass().getSuperclass().getDeclaredField("playerInfoMap");
			} catch (NoSuchFieldException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (SecurityException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			fs.setAccessible(true);
			try {
				playerInfoMapRef = (Map<UUID, NetworkPlayerInfo>) fs.get(this);
			} catch (IllegalArgumentException e) {
				e.printStackTrace();
			} catch (IllegalAccessException e) {
				e.printStackTrace();
			}

			playerInfoMapRef.put(player_info.getGameProfile().getId(), player_info);

		}

		super.handleSpawnPlayer(packetIn);
	}
```
This restores the rendering but the player names are lost (replaced by the first part of their uuid).

Since the UUIDs I have seen this on are all cracked, i think it could be the server, but who knows... we have a workaround here.

**Comment by couldbejake** [comment]
Try forking Minebot and pushing the modified code back to the original repo to get @michaelzangl's attention :).

**Comment by beppe9000** [comment]
I think that tagging @michaelzangl is just fine for catching his attenction... This was written more than one year ago so  I don't have the necessary things on this pc. Furthermore idk if that code has been updated.

**Comment by michaelzangl** [comment]
Should be fixed with new net handler interception interface in 1.15
