### ISSUE TITLE
/minebot plant sugar_cane Doesn't work!

### ISSUE THREAD

**Issue by Hury999** [michaelzangl/minebot#169]
So when i run /minebot plant sugar_cane, it crashes every time.

## Crash report:

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/26/17 9:09 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemBlock.field_150939_a from class net.famzangl.minecraft.minebot.ai.task.inventory.ItemWithSubtype
	at net.famzangl.minecraft.minebot.ai.task.inventory.ItemWithSubtype.getBlockType(ItemWithSubtype.java:112)
	at net.famzangl.minecraft.minebot.ai.BlockItemFilter.matchesItem(BlockItemFilter.java:54)
	at net.famzangl.minecraft.minebot.ai.BlockItemFilter.matches(BlockItemFilter.java:50)
	at net.famzangl.minecraft.minebot.ai.AIHelper.selectCurrentItem(AIHelper.java:532)
	at net.famzangl.minecraft.minebot.ai.task.place.PlaceBlockAtFloorTask.runTick(PlaceBlockAtFloorTask.java:81)
	at net.famzangl.minecraft.minebot.ai.strategy.TaskStrategy.onGameTick(TaskStrategy.java:191)
	at net.famzangl.minecraft.minebot.ai.strategy.PathFinderStrategy.onGameTick(PathFinderStrategy.java:98)
	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.strategyTick(StrategyStack.java:87)
	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.gameTick(StrategyStack.java:70)
	at net.famzangl.minecraft.minebot.ai.strategy.StackStrategy.onGameTick(StackStrategy.java:44)
	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
	at net.famzangl.minecraft.minebot.ai.AIController.onPlayerTick(AIController.java:211)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_AIController_onPlayerTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:346)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1701)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.famzangl.minecraft.minebot.ai.task.inventory.ItemWithSubtype.getBlockType(ItemWithSubtype.java:112)
	at net.famzangl.minecraft.minebot.ai.BlockItemFilter.matchesItem(BlockItemFilter.java:54)
	at net.famzangl.minecraft.minebot.ai.BlockItemFilter.matches(BlockItemFilter.java:50)
	at net.famzangl.minecraft.minebot.ai.AIHelper.selectCurrentItem(AIHelper.java:532)
	at net.famzangl.minecraft.minebot.ai.task.place.PlaceBlockAtFloorTask.runTick(PlaceBlockAtFloorTask.java:81)
	at net.famzangl.minecraft.minebot.ai.strategy.TaskStrategy.onGameTick(TaskStrategy.java:191)
	at net.famzangl.minecraft.minebot.ai.strategy.PathFinderStrategy.onGameTick(PathFinderStrategy.java:98)
	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.strategyTick(StrategyStack.java:87)
	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.gameTick(StrategyStack.java:70)
	at net.famzangl.minecraft.minebot.ai.strategy.StackStrategy.onGameTick(StackStrategy.java:44)
	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
	at net.famzangl.minecraft.minebot.ai.AIController.onPlayerTick(AIController.java:211)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_AIController_onPlayerTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:346)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['Hury'/1577, l='MpServer', x=10988.49, y=63.00, z=-7458.51], EntityOtherPlayerMP['EliteCommander99'/7134915, l='MpServer', x=10983.91, y=63.00, z=-7435.44], EntityOtherPlayerMP['NightKillerzz33'/3587181, l='MpServer', x=10992.91, y=63.00, z=-7425.44]]
	Chunk stats: MultiplayerChunkCache: 290, 290
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (10903,63,-7484), Chunk: (at 7,3,4 in 681,-468; contains blocks 10896,0,-7488 to 10911,255,-7473), Region: (21,-15; contains chunks 672,-480 to 703,-449, blocks 10752,0,-7680 to 11263,255,-7169)
	Level time: 608325388 game time, 608325388 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 11 total; [EntityPlayerSP['Hury'/1577, l='MpServer', x=10988.50, y=63.00, z=-7458.51], EntityPlayerSP['Hury'/1577, l='MpServer', x=10988.49, y=63.00, z=-7458.51], EntityOtherPlayerMP['EliteCommander99'/7134915, l='MpServer', x=10983.91, y=63.00, z=-7435.44], EntityOtherPlayerMP['NightKillerzz33'/3587181, l='MpServer', x=10992.91, y=63.00, z=-7425.44], EntitySkeleton['Skeleton'/7172377, l='MpServer', x=10951.50, y=32.00, z=-7496.50], EntityCreeper['Â§d2X Â§6CREEPER'/7762028, l='MpServer', x=10949.50, y=32.00, z=-7496.50], EntityOtherPlayerMP['NightKillerzz33'/3587181, l='MpServer', x=10992.91, y=63.00, z=-7425.44], EntityVillager['Dinnerbone'/5239236, l='MpServer', x=10957.13, y=63.00, z=-7438.59], EntityEnderman['Enderman'/7583231, l='MpServer', x=11000.50, y=27.00, z=-7496.50], EntityItemFrame['entity.ItemFrame.name'/5239234, l='MpServer', x=10989.50, y=65.50, z=-7436.03], EntityOtherPlayerMP['EliteCommander99'/7134915, l='MpServer', x=10983.91, y=63.00, z=-7435.44]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.12-SNAPSHOT:eab710b:1242) <- TacoSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2732)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 237177352 bytes (226 MB) / 524603392 bytes (500 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.40 Powered by Forge 14.21.0.2359 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2359.jar) 
	UCHIJA	forge{14.21.0.2359} [Minecraft Forge] (forge-1.12-14.21.0.2359.jar) 
	UCHIJA	minebot-mod{0.4} [Minebot] (Minebot-0.5.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.165.1' Renderer: 'AMD Radeon (TM) R9 380 Series'
	Launched Version: 1.12-forge1.12-14.21.0.2359
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R9 380 Series GL version 4.5.13474 Compatibility Profile Context 22.19.165.1, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
```

**Comment by michaelzangl** [comment]
Thanks, I'll have a look at it.
