### ISSUE TITLE
My bot doesnt work

### ISSUE THREAD

**Issue by Virtual-Vortex** [michaelzangl/minebot#176]
here is my crash report of what happend when i did /minebot mine

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 10/07/17 17:40
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.util.MovementInput cannot be cast to net.minecraft.util.MovementInputFromOptions
	at deez.togglesneak.PlayerBase.onLivingUpdate(PlayerBase.java:114)
	at api.player.client.ClientPlayerAPI.onLivingUpdate(Unknown Source)
	at api.player.client.ClientPlayerAPI.onLivingUpdate(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at deez.togglesneak.PlayerBase.onLivingUpdate(PlayerBase.java:114)
	at api.player.client.ClientPlayerAPI.onLivingUpdate(Unknown Source)
	at api.player.client.ClientPlayerAPI.onLivingUpdate(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 1988
	Entity Name: 09O
	Entity's Exact location: 247.58, 8.62, -7039.39
	Entity's Block location: World: (247,8,-7040), Chunk: (at 7,0,0 in 15,-440; contains blocks 240,0,-7040 to 255,255,-7025), Region: (0,-14; contains chunks 0,-448 to 31,-417, blocks 0,0,-7168 to 511,255,-6657)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['09O'/1988, l='MpServer', x=247.58, y=8.62, z=-7039.39]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-14833,255,14847), Chunk: (at 15,15,15 in -928,927; contains blocks -14848,0,14832 to -14833,255,14847), Region: (-29,28; contains chunks -928,896 to -897,927, blocks -14848,0,14336 to -14337,255,14847)
	Level time: 161821309 game time, 161927537 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['09O'/1988, l='MpServer', x=247.58, y=8.62, z=-7039.39]]
	Retry entities: 0 total; []
	Server brand: PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 153787192 bytes (146 MB) / 359198720 bytes (342 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D7 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHIJA	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
	UCHIJA	cpsmod{1.0} [CPSMod] (CPSMod.jar) 
	UCHIJA	minebot-mod{0.3.0} [Minebot] (Minebot-0.3.0.jar) 
	UCHIJA	ToggleSneak{3.0.3} [ToggleSneak] (ToggleSneak-(1.7.10)-v3.0.5.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4278' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.3.0 - Build 10.18.15.4278, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [!  §1§lC & C Blue v2]
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D7
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 10.18.15.4278
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by couldbejake** [comment]
The line
`at deez.togglesneak.PlayerBase.onLivingUpdate(PlayerBase.java:114)`

would suggest that its not Minebot thats broken.

These are the mods you currently have installed
`UCHIJA	PlayerAPI{1.4} [Player API] (minecraft.jar)
UCHIJA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar)
UCHIJA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar)
UCHIJA	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar)
UCHIJA	cpsmod{1.0} [CPSMod] (CPSMod.jar)
UCHIJA	minebot-mod{0.3.0} [Minebot] (Minebot-0.3.0.jar)
UCHIJA	ToggleSneak{3.0.3} [ToggleSneak] (ToggleSneak-(1.7.10)-v3.0.5.jar)`

Now from the error above it looks like the mod ToggleSneak is the one crashing.

Try removing the Mod "ToggleSneak" and restarting minecraft - It's very possible that this mod is interfering with some type of reflection being done by minebot, so I'd recommend running Minebot alone.

**Comment by michaelzangl** [comment]
This is a dupplicate of #173
