### ISSUE TITLE
When using /minebot plant the game crashes

### ISSUE THREAD

**Issue by Sopitive** [michaelzangl/minebot#206]
I was using /minebot plant to plant carrots and all the bot did was plant one carrot and the game crashed.

**Comment by ghost** [comment]
What version? Try the newest.

**Comment by Sopitive** [comment]
After testing a little bit with /minebot plant, I have determined that the game only crashes whenever you try to plant carrots and potatos. Sugarcane just doesn't work correctly, and the bot doesn't plant it at all. All the other crops (Wheat, netherwart, and beetroot) work just fine with no issues. I am using the latest version and made sure by redownloading it and extracting it again.

**Comment by Sopitive** [comment]
**Here is the crash report (after trying to plant carrots):**


---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/9/17 7:55 AM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.item.ItemSeedFood cannot be cast to net.minecraft.item.ItemSeeds
	at net.famzangl.minecraft.minebot.ai.path.PlantPathFinder$PlaceSeedsTask.applyToDelta(PlantPathFinder.java:76)
	at net.famzangl.minecraft.minebot.ai.strategy.PathFinderStrategy.onGameTick(PathFinderStrategy.java:107)
	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.strategyTick(StrategyStack.java:87)
	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.gameTick(StrategyStack.java:70)
	at net.famzangl.minecraft.minebot.ai.strategy.StackStrategy.onGameTick(StackStrategy.java:44)
	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
	at net.famzangl.minecraft.minebot.ai.AIController.onPlayerTick(AIController.java:212)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_AIController_onPlayerTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:346)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.famzangl.minecraft.minebot.ai.path.PlantPathFinder$PlaceSeedsTask.applyToDelta(PlantPathFinder.java:76)
	at net.famzangl.minecraft.minebot.ai.strategy.PathFinderStrategy.onGameTick(PathFinderStrategy.java:107)
	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.strategyTick(StrategyStack.java:87)
	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.gameTick(StrategyStack.java:70)
	at net.famzangl.minecraft.minebot.ai.strategy.StackStrategy.onGameTick(StackStrategy.java:44)
	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
	at net.famzangl.minecraft.minebot.ai.AIController.onPlayerTick(AIController.java:212)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_AIController_onPlayerTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:346)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['WyattPlayzMC'/145, l='MpServer', x=-268.69, y=63.94, z=-764.51]]
	Chunk stats: MultiplayerChunkCache: 567, 567
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-320,64,-341), Chunk: (at 0,4,11 in -20,-22; contains blocks -320,0,-352 to -305,255,-337), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 96721 game time, 24156 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityZombie['Zombie'/512, l='MpServer', x=-192.50, y=32.00, z=-795.50], EntityZombie['Zombie'/773, l='MpServer', x=-305.50, y=20.00, z=-727.50], EntityItemFrame['entity.ItemFrame.name'/264, l='MpServer', x=-353.50, y=67.50, z=-726.03], EntityItemFrame['entity.ItemFrame.name'/265, l='MpServer', x=-352.50, y=67.50, z=-726.03], EntityBat['Bat'/522, l='MpServer', x=-247.25, y=59.10, z=-762.55], EntityBat['Bat'/523, l='MpServer', x=-249.80, y=57.86, z=-765.47], EntitySheep['Sheep'/268, l='MpServer', x=-345.03, y=66.00, z=-748.51], EntityZombie['Zombie'/269, l='MpServer', x=-342.45, y=67.00, z=-736.76], EntitySpider['Spider'/781, l='MpServer', x=-308.50, y=46.00, z=-733.50], EntityZombie['Zombie'/782, l='MpServer', x=-309.50, y=46.00, z=-733.50], EntitySheep['Sheep'/271, l='MpServer', x=-299.76, y=64.00, z=-796.63], EntitySkeleton['Skeleton'/1042, l='MpServer', x=-203.50, y=11.00, z=-780.50], EntitySheep['Sheep'/278, l='MpServer', x=-328.21, y=64.00, z=-745.51], EntitySlime['Slime'/280, l='MpServer', x=-317.91, y=62.32, z=-761.49], EntitySheep['Sheep'/291, l='MpServer', x=-288.36, y=67.00, z=-762.76], EntitySheep['Sheep'/292, l='MpServer', x=-280.74, y=67.00, z=-766.55], EntitySkeleton['Skeleton'/293, l='MpServer', x=-272.21, y=67.00, z=-768.49], EntityCreeper['Creeper'/1061, l='MpServer', x=-336.50, y=15.00, z=-825.50], EntitySkeleton['Skeleton'/934, l='MpServer', x=-308.50, y=17.00, z=-707.50], EntitySkeleton['Skeleton'/935, l='MpServer', x=-308.50, y=17.00, z=-708.50], EntityChicken['Chicken'/297, l='MpServer', x=-336.10, y=63.00, z=-694.86], EntityCreeper['Creeper'/298, l='MpServer', x=-261.40, y=53.00, z=-758.81], EntityEnderman['Enderman'/1194, l='MpServer', x=-193.50, y=30.00, z=-776.50], EntitySkeleton['Skeleton'/299, l='MpServer', x=-246.73, y=54.00, z=-778.47], EntitySlime['Slime'/300, l='MpServer', x=-277.21, y=62.29, z=-781.92], EntitySpider['Spider'/556, l='MpServer', x=-317.50, y=25.00, z=-702.01], EntitySheep['Sheep'/301, l='MpServer', x=-244.75, y=64.00, z=-784.84], EntitySpider['Spider'/558, l='MpServer', x=-317.50, y=25.00, z=-699.91], EntityCreeper['Creeper'/303, l='MpServer', x=-213.50, y=37.00, z=-821.50], EntitySpider['Spider'/304, l='MpServer', x=-208.50, y=32.00, z=-829.50], EntityCreeper['Creeper'/561, l='MpServer', x=-321.50, y=19.00, z=-728.50], EntityZombie['Zombie'/310, l='MpServer', x=-259.52, y=60.00, z=-758.19], EntitySpider['Spider'/311, l='MpServer', x=-274.42, y=62.00, z=-767.90], EntitySkeleton['Skeleton'/312, l='MpServer', x=-253.92, y=52.97, z=-775.49], EntityPlayerSP['WyattPlayzMC'/145, l='MpServer', x=-268.69, y=63.94, z=-764.51], EntitySkeleton['Skeleton'/1081, l='MpServer', x=-237.50, y=29.00, z=-696.50], EntitySheep['Sheep'/318, l='MpServer', x=-335.70, y=65.00, z=-682.49], EntitySheep['Sheep'/319, l='MpServer', x=-283.56, y=63.09, z=-731.55], EntitySheep['Sheep'/320, l='MpServer', x=-249.23, y=64.00, z=-757.51], EntityBat['Bat'/321, l='MpServer', x=-246.25, y=59.10, z=-759.25], EntitySpider['Spider'/322, l='MpServer', x=-266.94, y=64.00, z=-755.05], EntityCreeper['Creeper'/323, l='MpServer', x=-271.18, y=63.09, z=-743.51], EntitySkeleton['Skeleton'/707, l='MpServer', x=-293.50, y=54.00, z=-727.30], EntitySpider['Spider'/1093, l='MpServer', x=-258.64, y=53.00, z=-769.34], EntitySpider['Spider'/1094, l='MpServer', x=-255.02, y=52.00, z=-764.45], EntitySpider['Spider'/328, l='MpServer', x=-296.50, y=63.00, z=-703.50], EntitySkeleton['Skeleton'/456, l='MpServer', x=-199.52, y=71.00, z=-696.79], EntityCreeper['Creeper'/459, l='MpServer', x=-193.46, y=80.00, z=-688.81], EntityBat['Bat'/1355, l='MpServer', x=-317.25, y=57.12, z=-751.46], EntityChicken['Chicken'/204, l='MpServer', x=-349.20, y=68.00, z=-799.47], EntityEnderman['Enderman'/1101, l='MpServer', x=-323.60, y=50.00, z=-764.30], EntitySkeleton['Skeleton'/1102, l='MpServer', x=-321.50, y=50.00, z=-761.50], EntitySkeleton['Skeleton'/1361, l='MpServer', x=-310.50, y=19.00, z=-712.50], EntityBat['Bat'/1107, l='MpServer', x=-323.25, y=52.00, z=-749.25], EntityBat['Bat'/1108, l='MpServer', x=-320.75, y=24.00, z=-740.25], EntityBat['Bat'/340, l='MpServer', x=-193.25, y=21.10, z=-775.25], EntitySheep['Sheep'/213, l='MpServer', x=-343.52, y=72.00, z=-783.27], EntitySheep['Sheep'/215, l='MpServer', x=-315.20, y=64.00, z=-803.52], EntityBat['Bat'/599, l='MpServer', x=-325.25, y=56.10, z=-748.43], EntitySheep['Sheep'/216, l='MpServer', x=-307.48, y=64.00, z=-805.24], EntityBat['Bat'/600, l='MpServer', x=-321.25, y=49.10, z=-755.47], EntityBat['Bat'/601, l='MpServer', x=-307.19, y=45.33, z=-751.17], EntitySheep['Sheep'/346, l='MpServer', x=-262.45, y=62.43, z=-696.61], EntitySheep['Sheep'/347, l='MpServer', x=-219.77, y=63.09, z=-726.44], EntitySheep['Sheep'/348, l='MpServer', x=-213.50, y=63.00, z=-748.50], EntitySkeleton['Skeleton'/1116, l='MpServer', x=-200.50, y=32.00, z=-828.50], EntitySheep['Sheep'/222, l='MpServer', x=-305.47, y=64.00, z=-795.63], EntitySheep['Sheep'/224, l='MpServer', x=-293.55, y=63.00, z=-801.83], EntityZombie['Zombie'/608, l='MpServer', x=-252.50, y=56.00, z=-776.50], EntitySheep['Sheep'/225, l='MpServer', x=-295.66, y=65.00, z=-803.62], EntityBat['Bat'/353, l='MpServer', x=-199.85, y=30.05, z=-770.74], EntitySkeleton['Skeleton'/746, l='MpServer', x=-310.50, y=19.00, z=-712.50], EntityCreeper['Creeper'/1390, l='MpServer', x=-320.50, y=57.00, z=-751.50], EntitySpider['Spider'/1135, l='MpServer', x=-190.81, y=33.00, z=-794.12], EntityCreeper['Creeper'/1391, l='MpServer', x=-323.50, y=57.00, z=-752.50], EntitySpider['Spider'/1136, l='MpServer', x=-192.30, y=33.00, z=-793.24], EntitySheep['Sheep'/243, l='MpServer', x=-253.17, y=63.00, z=-696.79], EntitySheep['Sheep'/244, l='MpServer', x=-258.27, y=63.09, z=-697.51], EntitySheep['Sheep'/245, l='MpServer', x=-253.24, y=63.00, z=-702.35], EntitySheep['Sheep'/246, l='MpServer', x=-245.80, y=63.00, z=-702.44], EntitySheep['Sheep'/247, l='MpServer', x=-225.50, y=63.00, z=-717.50], EntitySheep['Sheep'/248, l='MpServer', x=-232.76, y=63.00, z=-706.35], EntitySheep['Sheep'/249, l='MpServer', x=-227.15, y=63.00, z=-711.16], EntitySkeleton['Skeleton'/250, l='MpServer', x=-233.70, y=63.00, z=-705.44], EntityBat['Bat'/1021, l='MpServer', x=-278.58, y=13.11, z=-810.74], EntitySheep['Sheep'/255, l='MpServer', x=-208.71, y=64.00, z=-711.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 289449912 bytes (276 MB) / 730947584 bytes (697 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2406 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2406.jar) 
	UCHIJAAAA	forge{14.21.1.2406} [Minecraft Forge] (forge-1.12-14.21.1.2406.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UCHIJAAAA	minebot-mod{0.4} [Minebot] (Minebot-v1.12.2.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4542' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.12-forge1.12-14.21.1.2406
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4542, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

**Comment by ghost** [comment]
Again....
What version? Try the newest.

**Comment by Sopitive** [comment]
I am using the latest and newest version on Minecraft forge 1.12.

**Comment by ghost** [comment]
For me it all works perfect. I had the same isue in the first 1.12 Port but at the latest version, for me all works fine.
Sure u have newest version? Try to download it again.

**Comment by Sopitive** [comment]
Planting Wheat works just fine for me. I did download the mod again to make sure that I had the latest version. The crash happens when I type /minebot plant carrot or /minebot plant potato.
