### ISSUE TITLE
Can't run scripts using /minebot js path

### ISSUE THREAD

**Issue by EdgarTx** [michaelzangl/minebot#22]
When I try to run script it throws error (shown in launcher):

[23:13:14] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.command.CommandRegistry:interceptCommand:226]: Minebot handling command: /minebot js C:\Users\User\Desktop\minebot\test.txt
[23:13:14] [Client thread/INFO] [STDOUT] [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:75]: Data directory: C:\Users\User\AppData\Roaming\.minecraft\minebot
[23:13:14] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.AIController:requestUseStrategy:350]: Request to use net.famzangl.minecraft.minebot.ai.scripting.CommandJs$RunScriptStrategy@2a769291
[23:13:14] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.AIController:onPlayerTick:156]: Using new root strategy: net.famzangl.minecraft.minebot.ai.scripting.CommandJs$RunScriptStrategy@2a769291
Exception in thread "Thread-22" [23:13:14] [Thread-22/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[23:13:14] [Thread-22/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.famzangl.minecraft.minebot.ai.scripting.CommandJs$ScriptRunner.run(CommandJs.java:97)
[23:13:14] [Thread-22/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.lang.Thread.run(Thread.java:745)

**Comment by JOO200** [comment]
Try to take "/minebuild load <path>"
Maybe someone can change the post in the forum.

**Comment by michaelzangl** [comment]
The problem is that you JVM does not provide a javascript engine.

**Comment by wsidl** [comment]
I'm getting the same error. Just get "JS Error: No Javascript engine was found", but my copy of OpenJDK does come with Nashorn so it has a JS Engine:
```
> jjs -scripting
jjs> print('test');
test
jjs>
```
Thought I'd try patching, so I made a few changes in CommandJS.java:
```
25: import javax.script.ScriptException;
++: import jdk.nashorn.api.scripting.NashornScriptEngineFactory;

99: 				}
--: 				ScriptEngineManager manager = new ScriptEngineManager();
++:				NashornScriptEngineFactory factory = new NashornScriptEngineFactory();
--:				ScriptEngine engine = manager.getEngineByName("JavaScript");
++:				ScriptEngine engine = factory.getScriptEngine();
102: 				if (engine == null) {
```
But now I get a very quick "test.js : Running Script" blip on the screen and disappears. There's no error and no trace.

**Comment by wsidl** [comment]
you can also use your existing code, but switch 'Javascript' with 'nashorn':
````
--:             ScriptEngine engine = manager.getEngineByName("JavaScript");
++:             ScriptEngine engine = manager.getEngineByName("nashorn");
````

**Comment by michaelzangl** [comment]
What script are you using? Try doing an infinite while - loop:

    while(true) {}

This is what I would start debugging with. Debugging Javascript is a bit difficult. I also experienced some issues with Strings.

**Comment by wsidl** [comment]
Same thing. Changed the script to an empty while loop and still, the "Running Script" text will flash on and disappear.

**Comment by michaelzangl** [comment]
This is bad and means that your script engine is not really executing that script. I can't really help you debugging this. Normally you should at least see some form of error message.

**Comment by wsidl** [comment]
hmm, I'm not much of a Java developer, so don't know what I can try.
Tried the following changes:
````
118:				}
++:			} catch (Exception e){
++:				e.printStackTrace();
++:				synchronized (tickHelperMutex) {
++:					error = new StringTaskError(e.getMessage());
++:				}
119:			} finally {
````
````
106: 				engine.put("minescript", new MineScript(this));
--:				engine.eval(fis);
++:				engine.eval("while(true){}");
````
also commented out line 106.

I even tried putting a bunch of "System.out.print('test');" lines and nothing showed up. Know how I can add some text to print to the console? I'm trying to debug to see at what point it's failing. I have a feeling it might be somewhere in the MineScript class.

**Comment by michaelzangl** [comment]
Try to pull again. I added some debug output. On String concatenation, Java implicitly converts all values to Strings (even BlockPos, ...).

**Comment by wsidl** [comment]
Ok, don't know what you did differently, but everything works now. Tried using "walkTowards" and "displayChat". Getting the expected results.
None of the println commands are being run, so will have to use AIChatController.addChatLine() to generate any kind of output.

**Comment by michaelzangl** [comment]
println (and the javascript print) print to standard output. You can see it by enabling the game output in your launcher and telling the launcher to stay open.

**Comment by wsidl** [comment]
got it. thanks.
