### ISSUE TITLE
Custom mod blocks - only being mined 1 in a group

### ISSUE THREAD

**Issue by karobelle** [michaelzangl/minebot#231]
Hi all,

I added pixelmon:bauxite_ore to the .json file, and the mod is able to find bauxite. I noticed though, that it will only mine 1 bauxite in a group of at least 2+, and move on without mining the whole group in the vicinity. How do I get the bot to mine all of the bauxite that is nearby, and not just 1?

Also, if anyone knows, how do I get the bot to mine a pixelmon:fire_stone_ore that is always spawned above a block of lava? It seems to crash when i load the command /minebot mine pixelmon:fire_stone_ore. 

Thanks!

**Comment by gsquaredxc** [comment]
You cannot mine fire stone ore as it is above lava and removing the protections set up could possibly cause minebot to fall into the lava. You could remove those protections, but minebot would also not pick up the items due to other safety features which wouldn’t allow minebot to pick up the item. In order to pick up the item, you would need to go to the edge of the block while holding shift, then quickly grab the ore. This is not currently possible and would take a bit of work in order to do.

**Comment by karobelle** [comment]
Ok, that makes sense, thanks! What about the bauxite ore issue? I haven't found a way to get it to mine all of the ore in a group versus just 1 and moving on.

**Comment by michaelzangl** [comment]
Can you post a video of the wrong behavior?

**Comment by karobelle** [comment]
First case: ignored bauxite ore in front of itself, and went for a ore further below.
Second case: mined only one in the group.

Video is linked below:

https://streamable.com/c1nv7

Sometimes wont mine bauxite at all on a server. I think this was the error in the technic launcher logs:

18/06/18 17:33:46 [INFO]  [17:33:46] [main/FATAL]: Error executing task
[B#360] 2018/06/18 17:33:46 [INFO]  java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: index: 1, length: 85 (expected: range(0, 82))
[B#360] 2018/06/18 17:33:46 [INFO]  	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
[B#360] 2018/06/18 17:33:46 [INFO]  	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
[B#360] 2018/06/18 17:33:46 [INFO]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
[B#360] 2018/06/18 17:33:46 [INFO]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
[B#360] 2018/06/18 17:33:46 [INFO]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#360] 2018/06/18 17:33:46 [INFO]  Caused by: java.lang.IndexOutOfBoundsException: index: 1, length: 85 (expected: range(0, 82))
[B#360] 2018/06/18 17:33:46 [INFO]  	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1353) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
[B#360] 2018/06/18 17:33:46 [INFO]  	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1348) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
[B#360] 2018/06/18 17:33:46 [INFO]  	at io.netty.buffer.PooledUnsafeDirectByteBuf.internalNioBuffer(PooledUnsafeDirectByteBuf.java:331) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
[B#360] 2018/06/18 17:33:46 [INFO]  	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:630) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
[B#360] 2018/06/18 17:33:46 [INFO]  	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1213) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.network.PacketBuffer.toString(PacketBuffer.java:1289) ~[gy.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:380) ~[gy.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147240_a(NetHandlerPlayClient.java:1876) ~[brz.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:58) ~[iw.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:11) ~[iw.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
[B#360] 2018/06/18 17:33:46 [INFO]  	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
[B#360] 2018/06/18 17:33:46 [INFO]  	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
[B#360] 2018/06/18 17:33:46 [INFO]  	... 9 more
