### ISSUE TITLE
Crash when using /minebuild reverse

### ISSUE THREAD

**Issue by NicciZar** [michaelzangl/minebot#248]
My Minecraft client crashes when using the command /minebuild reverse (for creating these build scripts)
After logging into my world it just says that the script has been saved but its just an empty file..
I used /minebuild pos1 and pos2 to select the area with the building 

Im using Minecraft version 1.12.2

**Comment by CowArmy33** [comment]
Found a fix to this issue, use the command like this:
`/minebuild reverse *name*.txt`

Just replace *name* with what you want to call the script. I'm not sure why you would want to do this anyway because building from scripts doesn't really work.

**Comment by NicciZar** [comment]
Thanks for helping but my Minecraft Client still crashes when I try to use this command.

I dont know if there are any conflicts with other mods that I use but I dont think so because none change the way something is saved.. (havent read of any conflicts)

**Comment by michaelzangl** [comment]
Can you send the crash report / stack trace?

**Comment by NicciZar** [comment]
Yea sure. 
Thats what I do:
1. Load into Minecraft 1.12.2 Singleplayer /Multiplayer (none works)
2. Set two positions (/minebuild pos1 ; pos2 )
3. Use command (/minebuild reverse test.txt)
4. Minecraft Crashes 
5. Restart Minecraft and load into same world
6. "[Minebot] Output written to: C:\Users\.......\.minecraft\minebot\build\test.txt"

7. Crash Report: https://paste.dimdev.org/pikozuboba.mccrash 

8. Test.txt file: https://paste.dimdev.org/uluvuquyaq.shell 

If you want me to upload it somewhere else I can do that

**Comment by michaelzangl** [comment]
Thanks.

You seem to have stumbled accross something that was not ported to 1.12 yet.

I don't  have time to look into it, but just in case someone searches, the stack trace is:

```

java.lang.NullPointerException
    at net.famzangl.minecraft.minebot.build.reverse.factories.AbstractBuildTaskFactory.getTaskDescription(AbstractBuildTaskFactory.java:18)
    at net.famzangl.minecraft.minebot.build.reverse.factories.BuildTaskFactories.getTaskFor(BuildTaskFactories.java:38)
    at net.famzangl.minecraft.minebot.build.reverse.BuildReverser.addBuildPlace(BuildReverser.java:137)
    at net.famzangl.minecraft.minebot.build.reverse.BuildReverser.addRow(BuildReverser.java:126)
    at net.famzangl.minecraft.minebot.build.reverse.BuildReverser.run(BuildReverser.java:96)
    at net.famzangl.minecraft.minebot.build.reverse.RunReverseBuildStrategy.onGameTick(RunReverseBuildStrategy.java:49)
    at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:123)
    at net.famzangl.minecraft.minebot.ai.AIController.onPlayerTick(AIController.java:212)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_146_AIController_onPlayerTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1706)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3937)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by NicciZar** [comment]
Glad that I could help finding that.

**Comment by xpr0legendx** [comment]
Bit late, but thought it is worth noting that this bug will only occur when there are unsupported blocks in the area you try to reverse (such as pistons etc). If these blocks are not in the area, it will work perfectly fine.
> 
> 
> Found a fix to this issue, use the command like this:
> `/minebuild reverse *name*.txt`
> 
> Just replace _name_ with what you want to call the script. I'm not sure why you would want to do this anyway because building from scripts doesn't really work.
Using "/minebuild reverse name,txt" will not solve this issue.
