### ISSUE TITLE
Plant feature doesn't work when crops are on Y=1

### ISSUE THREAD

**Issue by Dampen59** [michaelzangl/minebot#304]
Hello,

The plant feature doesn't work when the crops are planted on dirt at layer 1.
I'm not sure what causes this bug but I think it's the farmland gap that puts the ground at Y=0.93750

Symptoms : 
When bot is placed on a crop and command /minebot plant is executed, it breaks the crop, replant it then totally hangs.
"An another strategy took over"
When putting a little farm area on layer Y=2 it runs just fine

Using Minebot 1.8, as 1.15.2 doesn't have the plant feature

**Comment by Dampen59** [comment]
Additional informations

**When bot stands on an already collected plant and /minebot plant is run :** 
`[10:44:13] [Client thread/INFO] [net.famzangl.minecraft.minebot.ai.command.CommandRegistry]: Evaluating: plant
[10:44:13] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:13] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:13] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:13] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:13] [Client thread/INFO] [net.famzangl.minecraft.minebot.ai.AIHelper]: Path finder did not find a path.
`

**When bot stands on an grown plant and /minebot plant is run :** 
`[10:44:23] [Client thread/INFO] [net.famzangl.minecraft.minebot.ai.command.CommandRegistry]: Evaluating: plant
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.path.world.WorldWithDelta:setPlayerPosition:151]: Set player position: BlockPos{x=-6222, y=1, z=2804}
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.path.world.WorldWithDelta:setBlockIdAndMeta:125]: Setblock at (-6222,1,2804) with 0:0
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.path.world.RecordingWorld:getTimeToDestroy:36]: TIME to destroy block at BlockPos{x=-6222, y=1, z=2804}: 0.0
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.path.world.WorldWithDelta:setBlockIdAndMeta:125]: Setblock at (-6222,1,2804) with 0:0
[10:44:23] [Client thread/WARN] [net.famzangl.minecraft.minebot.ai.path.world.BlockBounds]: Missing bounds for block+meta: 2263
[10:44:23] [Client thread/WARN] [net.famzangl.minecraft.minebot.ai.path.world.BlockBounds]: Missing bounds for block+meta: 2263
[10:44:23] [Client thread/WARN] [net.famzangl.minecraft.minebot.ai.path.world.BlockBounds]: Missing bounds for block+meta: 2263
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.settings.MinebotSettings:getDataDir:129]: Data directory: C:\Users\Dampen59\AppData\Roaming\.minecraft\minebot
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.InteractAlways:func_151468_f:45]: Sending key press event.
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.path.world.WorldWithDelta:setPlayerPosition:151]: Set player position: BlockPos{x=-6222, y=1, z=2804}
[10:44:23] [Client thread/INFO] [STDOUT]: [net.famzangl.minecraft.minebot.ai.InteractAlways:func_151468_f:45]: Sending key press event.
[10:44:23] [Client thread/INFO] [net.famzangl.minecraft.minebot.ai.AIHelper]: Path finder did not find a path.
[10:44:23] [Client thread/ERROR] [net.famzangl.minecraft.minebot.ai.strategy.AIStrategy]: Task sent desync. This is an error. Did the server lag?
[10:44:23] [Client thread/ERROR] [net.famzangl.minecraft.minebot.ai.strategy.AIStrategy]: Error: StringTaskError [message=An other strategy took over.]
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.Exception: Stack trace
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Thread.dumpStack(Unknown Source)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.famzangl.minecraft.minebot.ai.strategy.TaskStrategy.desync(TaskStrategy.java:87)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.famzangl.minecraft.minebot.ai.strategy.TaskStrategy.onDeactivate(TaskStrategy.java:71)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.setActive(AIStrategy.java:63)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.setCurrentStrategy(StrategyStack.java:99)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.famzangl.minecraft.minebot.ai.strategy.StrategyStack.gameTick(StrategyStack.java:76)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.famzangl.minecraft.minebot.ai.strategy.StackStrategy.onGameTick(StackStrategy.java:44)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.famzangl.minecraft.minebot.ai.strategy.AIStrategy.gameTick(AIStrategy.java:116)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.famzangl.minecraft.minebot.ai.AIController.onPlayerTick(AIController.java:214)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_AIController_onPlayerTick_ClientTickEvent.invoke(.dynamic)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:366)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1617)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:120)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:44:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:44:23] [Client thread/INFO]: [CHAT] [Minebot] Error: An other strategy took over.
[10:44:23] [Client thread/INFO] [net.famzangl.minecraft.minebot.ai.AIHelper]: Path finder did not find a path.
`
